version: '3'

services: 

  app:
    build: 
      context: ./node
      dockerfile: Dockerfile
    image: viniciosdb/node
    container_name: app
    networks: 
      - node-network
    tty: true
    depends_on: 
       - db

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    image: viniciosdb/nginx
    container_name: nginx
    networks: 
      - node-network
    ports: 
      - "8080:80"
    depends_on: 
      - app

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes: 
      - ./mysql:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network


networks: 
  node-network:
    driver: bridge    